In [1]:
import math
import numpy as np
from numpy import linalg

The Cholesky decomposition or Cholesky factorization is a decomposition of a Hermitian, positive-definite matrix into the product of a lower triangular matrix and its conjugate transpose, which is useful for efficient numerical solutions, e.g., Monte Carlo simulations

Note - We will work on real matrices

In [2]:
matrix = np.array([
    [4, 12, -16],
    [12, 37, -43],
    [-16, -43, 98]
])

### Step 1 -  Check if matrix is symmetric ###

In [3]:
def is_symmetric(matrix):
    
    # Check if the matrix is square
    if len(matrix) != len(matrix[0]):
        return False
    
    # Create the transpose of the matrix
    transpose_matrix = matrix.T
    
    # Compare the original matrix with its transpose
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] != transpose_matrix[i][j]:
                return False
    
    # If all elements match, the matrix is symmetric
    return True

In [4]:
if is_symmetric(matrix):
    print("The matrix is symmetric.")
else:
    print("The matrix is not symmetric.")

The matrix is symmetric.


In [5]:
# Check if the matrix is symmetric numpy method
if np.allclose(matrix, matrix.T):
    print(True)

True


### Step 2 - Check if matrix is positive definite ###

In [6]:
# for symmteric we can check positive definte by checking if all eigen values are positive
# Actual def: xTAx > 0

def is_positive_definite(matrix):
    
    # Check if the matrix is square
    if matrix.shape[0] != matrix.shape[1]:
        return False
    
    # Calculate the eigenvalues
    eigenvalues = np.linalg.eigvals(matrix)
    print(eigenvalues)
    
    # Check if all eigenvalues are positive
    if np.all(eigenvalues > 0):
        return True
    else:
        return False

In [7]:
if is_positive_definite(matrix):
    print("The matrix is positive definite.")
else:
    print("The matrix is not positive definite.")

[1.23477232e+02 1.88049805e-02 1.55039632e+01]
The matrix is positive definite.


### Step 3 - Cholesky Decomposition ###

In [8]:
decomp_matrix = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        if i== 0 and j == 0:
            decomp_matrix[i][j] = math.sqrt(matrix[i][j])
        if i==1 and j==0:
            decomp_matrix[i][j] = matrix[i][j]/decomp_matrix[0][0]
        if i==1 and j==1:
            decomp_matrix[i][j] = math.sqrt(matrix[i][j] - decomp_matrix[1][0]**2)
        if i==2 and j==0:
            decomp_matrix[i][j] = matrix[i][j]/decomp_matrix[0][0]
        if i==2 and j==1:
            decomp_matrix[i][j] = (matrix[i][j] - decomp_matrix[2][0]*decomp_matrix[1][0])/decomp_matrix[1][1]
        if i==2 and j==2:
            decomp_matrix[i][j] = math.sqrt(matrix[i][j] - decomp_matrix[2][0]**2 - decomp_matrix[2][1]**2)

In [9]:
decomp_matrix

[[2.0, 0, 0], [6.0, 1.0, 0], [-8.0, 5.0, 3.0]]

In [10]:
# cholesky decomposition numpy method
decomposition = np.linalg.cholesky(matrix)

In [11]:
print(decomposition)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
